version: '3'
services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    working_dir: /usr/src/app

